#!/usr/bin/env python3
"""safety_github.py — GitHub integration"""
import json, subprocess, sys
from datetime import datetime
from pathlib import Path
from typing import Optional

def _run(cmd, cwd):
    r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        print("  [WARN] " + r.stderr.strip()[:300])
    return r

def check_gh():
    try:
        return subprocess.run(["gh", "--version"], capture_output=True).returncode == 0
    except:
        return False

def create_pr(project_root, title=None):
    print("\n" + "=" * 60)
    print("  [GH] Create PR")
    print("=" * 60)
    if not check_gh():
        print("  FAIL: gh not installed. Install: winget install GitHub.cli"); return False
    branch = _run(["git", "branch", "--show-current"], project_root).stdout.strip()
    if not branch or branch == "main":
        print("  FAIL: not on dev branch"); return False
    remote = _run(["git", "remote", "-v"], project_root).stdout.strip()
    if not remote:
        print("  WARN: no remote configured"); return False
    print("  pushing " + branch + "...")
    _run(["git", "push", "-u", "origin", branch], project_root)
    pr_title = title or "Vibe Session: " + branch
    pr_body = "## AI-Assisted Changes\n\nAuto-generated by Vibe Safe Protocol\n\n### Branch\n`" + branch + "`\n\n---\n_This PR was automatically created_"
    result = _run(["gh", "pr", "create", "--title", pr_title, "--body", pr_body, "--base", "main", "--head", branch], project_root)
    if result.returncode == 0:
        print("  OK: PR created")
        for line in result.stdout.split("\n"):
            if line.startswith("https://"):
                print("    " + line.strip()); break
        return True
    else:
        print("  FAIL: PR creation"); return False

def push_tags(project_root):
    r = _run(["git", "push", "--tags"], project_root)
    print("  [GH] " + ("tags pushed OK" if r.returncode == 0 else "tags push FAIL"))

def check_status(project_root):
    print("\n[GH Status]")
    remote = _run(["git", "remote", "-v"], project_root).stdout.strip()
    if remote:
        print("  remote: configured")
    else:
        print("  remote: not configured")
    if check_gh():
        r = _run(["gh", "status"], project_root)
        if r.stdout:
            print("  gh: " + r.stdout[:300])
    r = _run(["git", "log", "--oneline", "@{u}..HEAD", "--"], project_root)
    if r.stdout.strip():
        print("  unpushed: " + r.stdout.strip()[:200])
    else:
        print("  all pushed")

def setup_remote(project_root, repo_name, org=None):
    if not check_gh():
        print("  FAIL: need gh CLI"); return False
    cmd = ["gh", "repo", "create", repo_name, "--private", "--source=.", "--remote=origin", "--push"]
    if org:
        cmd.insert(4, "--org=" + org)
    r = _run(cmd, project_root)
    if r.returncode == 0:
        print("  OK: repo created: " + repo_name)
        _run(["git", "push", "--tags"], project_root); return True
    else:
        print("  FAIL"); return False
